debug

diff --git a/.github/workflows/update-index.yml b/.github/workflows/update-index.yml
--- a/.github/workflows/update-index.yml
+++ b/.github/workflows/update-index.yml
@@ -21,30 +21,31 @@ jobs:
           echo "$PKG_REPO_OWNER"
           echo "$PKG_REPO"
           set -x
-          if [ ! -d ${PKG_REPO} ] # Check for package directory
-          then
-            echo "Package directory doesn't exist, creating now:
-            mkdir -p "${PKG_REPO}"
-            touch "${PKG_REPO}/index.html"
-          fi
-          if ! grep -w "$PKG_REPO" "index.html" # Check for package listing
-          then
-            echo "Package listing missing, creating"
-            sed -i '' "1s/.*/<div class=\"package\">\n<a href=\"$PKG_REPO\/\">$PKG_REPO<\/a><\/br>/" index.html
-          fi
-          if grep -w "$TAG_NAME" "$PKG_REPO/index.html" # Check for package version
-          then
-            echo "A package with this version already exists: $TAG_NAME"
-            exit 1
-          fi
-          # Insert new package at line 1 of the index.html file. This is to ensure the newest package is grabbed by pip install without a pinned version
-          cat << EOF | cat - "$PKG_REPO/index.html" > temp && mv temp "$PKG_REPO/index.html"
-          <a href="git+https://github.com/${PKG_REPO_OWNER}/${PKG_REPO}.git@${TAG_NAME}#egg=${PKG_REPO}-${TAG_NAME}" data-requires-python="&gt;=3.6.0">${PKG_REPO}-${TAG_NAME}</a><br/>
-          EOF
-          cat "$PKG_REPO/index.html"
-          git config user.name github-actions
-          git config user.email github-actions@github.com
-          git add "$PKG_REPO/index.html"
-          git status
-          git commit -m "Inserted ${PKG_REPO}-${TAG_NAME}"
-          git push
+          sed -i '' "1s/.*/<div class=\"package\">\n<a href=\"$PKG_REPO\/\">$PKG_REPO<\/a><\/br>/" index.html
+#           if [ ! -d ${PKG_REPO} ] # Check for package directory
+#           then
+#             echo "Package directory doesn't exist, creating now:
+#             mkdir -p "${PKG_REPO}"
+#             touch "${PKG_REPO}/index.html"
+#           fi
+#           if ! grep -w "$PKG_REPO" "index.html" # Check for package listing
+#           then
+#             echo "Package listing missing, creating"
+#             sed -i '' "1s/.*/<div class=\"package\">\n<a href=\"$PKG_REPO\/\">$PKG_REPO<\/a><\/br>/" index.html
+#           fi
+#           if grep -w "$TAG_NAME" "$PKG_REPO/index.html" # Check for package version
+#           then
+#             echo "A package with this version already exists: $TAG_NAME"
+#             exit 1
+#           fi
+#           # Insert new package at line 1 of the index.html file. This is to ensure the newest package is grabbed by pip install without a pinned version
+#           cat << EOF | cat - "$PKG_REPO/index.html" > temp && mv temp "$PKG_REPO/index.html"
+#           <a href="git+https://github.com/${PKG_REPO_OWNER}/${PKG_REPO}.git@${TAG_NAME}#egg=${PKG_REPO}-${TAG_NAME}" data-requires-python="&gt;=3.6.0">${PKG_REPO}-${TAG_NAME}</a><br/>
+#           EOF
+#           cat "$PKG_REPO/index.html"
+#           git config user.name github-actions
+#           git config user.email github-actions@github.com
+#           git add "$PKG_REPO/index.html"
+#           git status
+#           git commit -m "Inserted ${PKG_REPO}-${TAG_NAME}"
+#           git push
